### ISSUE TITLE
Xcode 11 GM support

### ISSUE THREAD

**Issue by alex-kovalenko** [Estimote/iOS-Proximity-SDK#48]
Hi!

When can we expect Xcode 11 GM support? 

Thanks,
Alex.

**Comment by trusk89** [comment]
On my current implementation `onEnter` is never called on iOS 13.

**Comment by heypiotr** [comment]
Is that in the foreground or background? Does your app have correct permissions? Note that on iOS 13, you need the new Bluetooth permission.

**Comment by trusk89** [comment]
@heypiotr that's in the foreground? Yeah, I;ve added `NSBluetoothAlwaysUsageDescription` permission and it successfully asks for permission at first launch.

**Comment by chwastek** [comment]
@trusk89 
1. is it iOS 13 or 13.1 beta 3? 
2. I assume there is simply no action at all once observer start to work? (no crashes but nothing happens basically?)

**Comment by trusk89** [comment]
@chwastek 

1. 13.1
2. exactly

**Comment by heypiotr** [comment]
The problem was actually in the "EstimoteBluetoothScanning" library, a low-level library that the Proximity SDK uses for low-level Bluetooth scanning. We've just released version 1.0.6 of that library with iOS 13 fixes, so you should be able to simply run `pod update EstimoteBluetoothScanning` in your project to fetch this latest version.

We'll also be releasing stable 1.5.0 later today or tomorrow, built with Xcode 11 GM, and with EstimoteBluetoothScanning requirement bumped to 1.0.6.

**Comment by heypiotr** [comment]
1.5.0 is out :tada: 

https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.5.0

Thanks all for your help/reports!
