### ISSUE TITLE
Xcode 12.0 beta 3 error:  Failed to build module EstimoteProximitySDK 

### ISSUE THREAD

**Issue by denisiaenasescu** [Estimote/iOS-Proximity-SDK#60]
Hello,
I'm trying to build an app with Xcode 12.0 beta 3, but it fails with the following error:

Failed to build module 'EstimoteProximitySDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)'

I am using EstimoteProximitySDK version 1.7.0.
I think it needs a fix from the SDK side. Do you know when a version that fixes this issue will be released? 

Thanks!

**Comment by KPatel91** [comment]
I am quite new to iOS development especially in the third-party dependency space - but it seems like upgrading to the latest version of Swift / XCode is a horrible process in iOS land and developers choose to upgrade late or even *shudder* keep **multiple versions of XCode on hand**.

This need for third-party dependencies to be built and made available for the latest version must seriously hamper the third-party ecosytem usage in Swift world as you can imagine a successive chain of libraries not being able to be built because a sub-dependency is not ready yet - leading developers to just "wait it out" an arbitrary time until they imagine their projects dependencies are now available for the latest versions.

I know that in a more recent version of Swift they have enabled a checkbox option for developers of libraries to NOT have to upgrade, but it seems Estimote and another few hardware integration libraries I use have decided not to enable this option - for reasons I don't understand due to my limited understanding of Swift.

I hope I have got this wrong and am missing something obvious, because out of a variety of languages / ecosystems I use this is literally the only one where even minor upgrades can break a build, and now my project's development is hampered.

Back to Xcode 11.6....
